#!/bin/bash
#Script de execução de c#

#Autor: Gustavo Sobreira
#Data: 22/05/2022
#Versão: 1.0.1
#Name: RodaC#
#Descrição: Script de execução de C# em ambiente linux para melhor rendimento.

#Necessário Mono,.net Core e vscode via terminal

echo "          ==========================================================="
echo "                            DIRETÓRIOS DISPONÍVEIS"
echo "          ==========================================================="
echo ""
echo ""

#Altere o caminho para o diretório desjado na sua máquina
CAMINHO=/home/sobreira/Documentos/Cursos/Alura/C#

#Vai até o destino
cd $CAMINHO
ls -Cc 
echo ""
echo ""

#Todos meus diretórios desta pasta recebem um número e um nome após
# 2_Criar_Calculadora

#Fiz assim para que não precise digitar todo o caminho do arquivo
read -p " --> DIGA O NÚMERO DO DIRETÓRIO ESCOLHIDO: " numero

#Localização do arquivo
cd $numero*

while true; do
    clear
    echo "          ==========================================================="
    echo "                                CONTEÚDO DIRETÓRIO   "
    echo "          ==========================================================="
    echo " "
    ls
    echo " "

    
    read -p " --> DESEJA EXECUTAR / BUILDAR / COMPILAR O ARQUIVO? [ E / B / C ]" acao
    case $acao in
        [Ee]*)
            clear
            echo "          ==========================================================="
            echo "                                   EXECUTANDO   "
            echo "          ==========================================================="
            echo " "
            mono *.exe;;
        
        [Bb]*)
            clear
            code *.cs
            echo "          ==========================================================="
            echo "                                   RODANDO CÓDIGO   "
            echo "          ==========================================================="
            echo " "
            dotnet build ; dotnet run;;
        
        [Cc]*)
            csc *.cs;;
    esac
    read -p " --> DESEJA FECHAR O PROGRAMA? [ S / N ]" sair
    case $sair in
        [Ss]*)
            break;;
        *)
        clear;;
    esac    
done